import fs from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { FILES_DIR } from "@/lib/db";
import { getBook, getChapters, getChapter } from "@/lib/books";
import { currentUserId, noSession } from "@/lib/session";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Ctx = { params: Promise<{ id: string }> };

function safeName(title: string, ext: string) {
  const base = title.replace(/[^\p{L}\p{N} .-]/gu, "").trim().slice(0, 80) || "book";
  return `${base}.${ext}`;
}

/** Rebuild a plain-text edition when we have no stored original (rare). */
function asPlainText(userId: number, id: number, title: string, author: string) {
  const lines = [title, author && `by ${author}`, "", ""].filter(Boolean);
  for (const { idx } of getChapters(userId, id)) {
    const c = getChapter(userId, id, idx);
    if (!c) continue;
    lines.push(c.title, "");
    lines.push(
      c.html
        .replace(/<\/(p|h[1-6]|li|blockquote|div)>/gi, "\n\n")
        .replace(/<br\s*\/?>/gi, "\n")
        .replace(/<[^>]+>/g, "")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/\n{3,}/g, "\n\n")
        .trim(),
      "",
    );
  }
  return lines.join("\n");
}

export async function GET(_req: Request, { params }: Ctx) {
  const userId = await currentUserId();
  if (!userId) return noSession();

  const id = Number((await params).id);
  const book = getBook(userId, id);
  if (!book) return NextResponse.json({ error: "Book not found." }, { status: 404 });

  if (book.file_name) {
    // file_name is generated by us, never user-supplied — but resolve and
    // re-check anyway so a bad DB row can't escape the files directory.
    const full = path.resolve(/*turbopackIgnore: true*/ FILES_DIR, book.file_name);
    if (full.startsWith(path.resolve(FILES_DIR) + path.sep)) {
      try {
        const buf = await fs.readFile(full);
        const ext = book.file_ext || "bin";
        return new NextResponse(new Uint8Array(buf), {
          headers: {
            "Content-Type":
              ext === "epub" ? "application/epub+zip" : ext === "pdf" ? "application/pdf" : "text/plain; charset=utf-8",
            "Content-Disposition": `attachment; filename="${safeName(book.title, ext)}"`,
            "Content-Length": String(buf.byteLength),
          },
        });
      } catch {
        // fall through to the generated text edition
      }
    }
  }

  const text = asPlainText(userId, id, book.title, book.author);
  return new NextResponse(text, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${safeName(book.title, "txt")}"`,
    },
  });
}
